/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles.componentes;

import index.Veontec;
import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author victo
 */
public class PanelCardMiProducto extends javax.swing.JPanel {

    /**
     * Creates new form PanelCard
     */
    public PanelCardMiProducto() {
        initComponents();
        Dimension tam = new Dimension(654, 236);
        this.setPreferredSize( tam );
        this.setSize( tam );
        this.panelBackground.setBackground(new Color(40,175,176));
        this.panelBackground.setEnabled(true);
        this.panelBackground.setVisible(true);
        
        
        Dimension tamImg = new Dimension(200, 236);
        this.pnImgPortafa.setSize(tamImg);
        this.pnImgPortafa.setPreferredSize(tamImg);
       
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelBackground = new vista.componentes.jpanelbackground.JPanelBackground();
        pnImgPortafa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        etqTitulo = new vista.componentes.etiqueta.Etiqueta();
        etqPrecioUnidad = new vista.componentes.etiqueta.Etiqueta();
        etqStockDisponible = new vista.componentes.etiqueta.Etiqueta();
        cmpPrecioUnidad = new vista.componentes.campos.CampoTexto();
        cmpStockDisponible = new vista.componentes.campos.CampoTexto();
        jScrollPane1 = new javax.swing.JScrollPane();
        cmpDetalleMiProducto = new javax.swing.JTextArea();
        btnEliminar = new vista.componentes.boton.Boton();
        btnEditar = new vista.componentes.boton.Boton();
        etqFecha = new vista.componentes.etiqueta.Mensaje();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(204, 204, 204));

        panelBackground.setBackground(new java.awt.Color(40, 175, 176));
        panelBackground.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray));
        panelBackground.setImgOpacidad(1.0F);
        panelBackground.setImgRutaInternoActivo(false);

        pnImgPortafa.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sin imagen");

        javax.swing.GroupLayout pnImgPortafaLayout = new javax.swing.GroupLayout(pnImgPortafa);
        pnImgPortafa.setLayout(pnImgPortafaLayout);
        pnImgPortafaLayout.setHorizontalGroup(
            pnImgPortafaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnImgPortafaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnImgPortafaLayout.setVerticalGroup(
            pnImgPortafaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnImgPortafaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(95, 95, 95))
        );

        etqTitulo.setForeground(new java.awt.Color(255, 255, 255));
        etqTitulo.setText("Titulo del producto para vender el la tienda");

        etqPrecioUnidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etqPrecioUnidad.setText("Precio x Unidad");

        etqStockDisponible.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etqStockDisponible.setText("Stock disponible");

        cmpPrecioUnidad.setEditable(false);
        cmpPrecioUnidad.setBorder(null);
        cmpPrecioUnidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cmpPrecioUnidad.setText("199.98");
        cmpPrecioUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpPrecioUnidadActionPerformed(evt);
            }
        });

        cmpStockDisponible.setEditable(false);
        cmpStockDisponible.setBorder(null);
        cmpStockDisponible.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cmpStockDisponible.setText("15");
        cmpStockDisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpStockDisponibleActionPerformed(evt);
            }
        });

        cmpDetalleMiProducto.setEditable(false);
        cmpDetalleMiProducto.setColumns(20);
        cmpDetalleMiProducto.setRows(5);
        cmpDetalleMiProducto.setEnabled(false);
        jScrollPane1.setViewportView(cmpDetalleMiProducto);

        btnEliminar.setImgButtonType("danger");
        btnEliminar.setTexto("Eliminar");

        btnEditar.setImgButtonType("warning");
        btnEditar.setTexto("Editar");

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                .addComponent(pnImgPortafa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etqTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etqStockDisponible, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmpStockDisponible, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmpPrecioUnidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(etqPrecioUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                    .addComponent(etqFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etqTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etqFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(etqStockDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmpStockDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(etqPrecioUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmpPrecioUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnImgPortafa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmpPrecioUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpPrecioUnidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpPrecioUnidadActionPerformed

    private void cmpStockDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpStockDisponibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpStockDisponibleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public vista.componentes.boton.Boton btnEditar;
    public vista.componentes.boton.Boton btnEliminar;
    public javax.swing.JTextArea cmpDetalleMiProducto;
    public vista.componentes.campos.CampoTexto cmpPrecioUnidad;
    public vista.componentes.campos.CampoTexto cmpStockDisponible;
    public vista.componentes.etiqueta.Mensaje etqFecha;
    private vista.componentes.etiqueta.Etiqueta etqPrecioUnidad;
    private vista.componentes.etiqueta.Etiqueta etqStockDisponible;
    public vista.componentes.etiqueta.Etiqueta etqTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private vista.componentes.jpanelbackground.JPanelBackground panelBackground;
    public javax.swing.JPanel pnImgPortafa;
    // End of variables declaration//GEN-END:variables
}
