/*
 * Copyright (C) 2021 victor
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package vista.ventanas;

/**
 *
 * @author victor
 */
public class VentanaHome extends javax.swing.JFrame {

    /**
     * Creates new form VentanaHome
     */
    public VentanaHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTabMenu = new javax.swing.JTabbedPane();
        pnTabBienvenida = new vista.componentes.jpanelbackground.JPanelBackground();
        panelHome = new vista.paneles.PanelBienvenida();
        pnTabMiTienda = new vista.componentes.jpanelbackground.JPanelBackground();
        pnMiTienda = new vista.paneles.PanelMiTienda();
        pnTabCompras = new vista.componentes.jpanelbackground.JPanelBackground();
        pnCompras = new vista.paneles.PanelCompras();
        pnTabVentas = new vista.componentes.jpanelbackground.JPanelBackground();
        pnVentas = new vista.paneles.PanelVentas();
        pnTabPreguntas = new vista.componentes.jpanelbackground.JPanelBackground();
        panelPreguntas = new vista.paneles.PanelPreguntas();
        pnTabCuenta = new vista.componentes.jpanelbackground.JPanelBackground();
        pnMiCuenta = new vista.paneles.PanelMiCuenta();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnTabMenu.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        javax.swing.GroupLayout pnTabBienvenidaLayout = new javax.swing.GroupLayout(pnTabBienvenida);
        pnTabBienvenida.setLayout(pnTabBienvenidaLayout);
        pnTabBienvenidaLayout.setHorizontalGroup(
            pnTabBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnTabBienvenidaLayout.setVerticalGroup(
            pnTabBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnTabMenu.addTab("Inicio", pnTabBienvenida);

        javax.swing.GroupLayout pnTabMiTiendaLayout = new javax.swing.GroupLayout(pnTabMiTienda);
        pnTabMiTienda.setLayout(pnTabMiTiendaLayout);
        pnTabMiTiendaLayout.setHorizontalGroup(
            pnTabMiTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMiTienda, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        pnTabMiTiendaLayout.setVerticalGroup(
            pnTabMiTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMiTienda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnTabMenu.addTab("Mi tienda", pnTabMiTienda);

        javax.swing.GroupLayout pnTabComprasLayout = new javax.swing.GroupLayout(pnTabCompras);
        pnTabCompras.setLayout(pnTabComprasLayout);
        pnTabComprasLayout.setHorizontalGroup(
            pnTabComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCompras, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        pnTabComprasLayout.setVerticalGroup(
            pnTabComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCompras, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
        );

        pnTabMenu.addTab("Compras", pnTabCompras);

        javax.swing.GroupLayout pnTabVentasLayout = new javax.swing.GroupLayout(pnTabVentas);
        pnTabVentas.setLayout(pnTabVentasLayout);
        pnTabVentasLayout.setHorizontalGroup(
            pnTabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnVentas, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        pnTabVentasLayout.setVerticalGroup(
            pnTabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnVentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnTabMenu.addTab("Ventas", pnTabVentas);

        javax.swing.GroupLayout pnTabPreguntasLayout = new javax.swing.GroupLayout(pnTabPreguntas);
        pnTabPreguntas.setLayout(pnTabPreguntasLayout);
        pnTabPreguntasLayout.setHorizontalGroup(
            pnTabPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPreguntas, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        pnTabPreguntasLayout.setVerticalGroup(
            pnTabPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPreguntas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnTabMenu.addTab("Preguntas", pnTabPreguntas);

        javax.swing.GroupLayout pnTabCuentaLayout = new javax.swing.GroupLayout(pnTabCuenta);
        pnTabCuenta.setLayout(pnTabCuentaLayout);
        pnTabCuentaLayout.setHorizontalGroup(
            pnTabCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMiCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        pnTabCuentaLayout.setVerticalGroup(
            pnTabCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMiCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnTabMenu.addTab("Mi cuenta", pnTabCuenta);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 727, Short.MAX_VALUE)
        );

        pnTabMenu.addTab("tab7", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTabMenu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTabMenu, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    public vista.paneles.PanelBienvenida panelHome;
    public vista.paneles.PanelPreguntas panelPreguntas;
    public vista.paneles.PanelCompras pnCompras;
    public vista.paneles.PanelMiCuenta pnMiCuenta;
    public vista.paneles.PanelMiTienda pnMiTienda;
    public vista.componentes.jpanelbackground.JPanelBackground pnTabBienvenida;
    public vista.componentes.jpanelbackground.JPanelBackground pnTabCompras;
    public vista.componentes.jpanelbackground.JPanelBackground pnTabCuenta;
    public javax.swing.JTabbedPane pnTabMenu;
    public vista.componentes.jpanelbackground.JPanelBackground pnTabMiTienda;
    public vista.componentes.jpanelbackground.JPanelBackground pnTabPreguntas;
    public vista.componentes.jpanelbackground.JPanelBackground pnTabVentas;
    public vista.paneles.PanelVentas pnVentas;
    // End of variables declaration//GEN-END:variables
}
