/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles;

import index.Veontec;
import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author victo
 */
public class PanelCardProducto extends javax.swing.JPanel {

    /**
     * Creates new form PanelCard
     */
    public PanelCardProducto() {
        initComponents();
        Dimension tam = new Dimension(654, 214);
        this.setPreferredSize( tam );
        this.setSize( tam );
        this.panelBackground.setBackground(new Color(40,175,176));
        this.panelBackground.setEnabled(true);
        this.panelBackground.setVisible(true);
       
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelBackground = new vista.componentes.jpanelbackground.JPanelBackground();
        pnImagen = new javax.swing.JPanel();
        etqTitulo = new vista.componentes.etiqueta.Etiqueta();
        etqPrecioUnidad = new vista.componentes.etiqueta.Etiqueta();
        etqStockDisponible = new vista.componentes.etiqueta.Etiqueta();
        cmpPrecioUnidad = new vista.componentes.campos.CampoTexto();
        cmpStockDisponible = new vista.componentes.campos.CampoTexto();
        jScrollPane1 = new javax.swing.JScrollPane();
        cmpDetalleProducto = new javax.swing.JTextArea();
        btnHacerCompra = new vista.componentes.boton.Boton();
        btnHacerPregunta = new vista.componentes.boton.Boton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(204, 204, 204));

        panelBackground.setBackground(new java.awt.Color(40, 175, 176));
        panelBackground.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray));
        panelBackground.setImgOpacidad(1.0F);
        panelBackground.setImgRutaInternoActivo(false);

        pnImagen.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnImagenLayout = new javax.swing.GroupLayout(pnImagen);
        pnImagen.setLayout(pnImagenLayout);
        pnImagenLayout.setHorizontalGroup(
            pnImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        pnImagenLayout.setVerticalGroup(
            pnImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        etqTitulo.setForeground(new java.awt.Color(255, 255, 255));
        etqTitulo.setText("Titulo del producto para vender el la tienda");

        etqPrecioUnidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etqPrecioUnidad.setText("Precio x Unidad");

        etqStockDisponible.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etqStockDisponible.setText("Stock disponible");

        cmpPrecioUnidad.setEditable(false);
        cmpPrecioUnidad.setBorder(null);
        cmpPrecioUnidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cmpPrecioUnidad.setText("199.98");
        cmpPrecioUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpPrecioUnidadActionPerformed(evt);
            }
        });

        cmpStockDisponible.setEditable(false);
        cmpStockDisponible.setBorder(null);
        cmpStockDisponible.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cmpStockDisponible.setText("15");
        cmpStockDisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpStockDisponibleActionPerformed(evt);
            }
        });

        cmpDetalleProducto.setColumns(20);
        cmpDetalleProducto.setRows(5);
        cmpDetalleProducto.setText("<Vendedor>\n<FechaDePublicacion>\n\n<Descripcion>");
        jScrollPane1.setViewportView(cmpDetalleProducto);

        btnHacerCompra.setImgButtonType("success");
        btnHacerCompra.setTexto("Hacer compra");

        btnHacerPregunta.setTexto("Hacer pregunta");

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addComponent(pnImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etqStockDisponible, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmpStockDisponible, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmpPrecioUnidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(etqPrecioUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(etqTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(btnHacerCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHacerPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etqTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(etqStockDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmpStockDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(etqPrecioUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmpPrecioUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHacerCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHacerPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(pnImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmpPrecioUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpPrecioUnidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpPrecioUnidadActionPerformed

    private void cmpStockDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpStockDisponibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpStockDisponibleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public vista.componentes.boton.Boton btnHacerCompra;
    public vista.componentes.boton.Boton btnHacerPregunta;
    public javax.swing.JTextArea cmpDetalleProducto;
    public vista.componentes.campos.CampoTexto cmpPrecioUnidad;
    public vista.componentes.campos.CampoTexto cmpStockDisponible;
    private vista.componentes.etiqueta.Etiqueta etqPrecioUnidad;
    private vista.componentes.etiqueta.Etiqueta etqStockDisponible;
    public vista.componentes.etiqueta.Etiqueta etqTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private vista.componentes.jpanelbackground.JPanelBackground panelBackground;
    public javax.swing.JPanel pnImagen;
    // End of variables declaration//GEN-END:variables
}
